/**
 * One-time bootstrap: generates supabase/seed.sql from the existing mock data in
 * /data, so the live database starts out visually identical to the current
 * mock-data-driven site. Run with `npx tsx scripts/generate-seed.ts > supabase/seed.sql`.
 *
 * Resolves everything through natural keys (slug/sku) via SQL subqueries rather than
 * pre-computing UUIDs, so it never needs to track ids itself.
 *
 * This is transitional tooling — once real catalogue data is entered (via the admin
 * panel or directly in Supabase), this script and its output are no longer the
 * source of truth and can be deleted.
 */
import { categories } from "../data/categories";
import { collections } from "../data/collections";
import { products } from "../data/products";
import { deals } from "../data/deals";
import { getCostPrice } from "../data/products";
import type { ImageRef, Product } from "../lib/types";

function sql(value: string) {
  return `'${value.replace(/'/g, "''")}'`;
}

function arr(values: string[]) {
  return `array[${values.map(sql).join(", ")}]`;
}

function placeholderPath(image: ImageRef) {
  return `placeholder:${image.kind ?? "editorial"}:${image.tone ?? "sand"}:${image.id}`;
}

// Illustrative-only tagging for the new "For Men" audience collection, since no
// product in the mock catalogue was ever tagged that way — pending real curation.
const FOR_MEN_SLUGS = ["imara-signet-ring", "sable-cuff-bracelet", "karibu-chain-bracelet", "tembo-link-bracelet"];

function materialFinishSlugs(product: Product): string[] {
  const text = product.materials.join(" ").toLowerCase();
  const slugs: string[] = [];
  if (text.includes("silver")) slugs.push("silver");
  if (text.includes("gold") || text.includes("brass") || text.includes("vermeil")) slugs.push("gold-brass");
  return slugs;
}

const lines: string[] = [];
lines.push("-- Generated by scripts/generate-seed.ts from /data mock content. See that file for regeneration.");
lines.push("begin;");
lines.push("");

// Categories
lines.push("-- Categories");
categories.forEach((c, i) => {
  lines.push(
    `insert into public.categories (slug, name, sort_order) values (${sql(c.slug)}, ${sql(c.name)}, ${i}) on conflict (slug) do nothing;`
  );
});
lines.push("");

// Collections (+ the new For Men audience collection, not present in mock data)
lines.push("-- Collections");
collections.forEach((c, i) => {
  lines.push(
    `insert into public.collections (slug, name, description, sort_order) values (${sql(c.slug)}, ${sql(c.name)}, ${sql(c.description ?? "")}, ${i}) on conflict (slug) do nothing;`
  );
});
lines.push(
  `insert into public.collections (slug, name, description, audience, sort_order) values ('for-men', 'For Men', 'Pieces suited to a men''s edit.', 'men', ${collections.length}) on conflict (slug) do nothing;`
);
lines.push("");

// Material finishes required by the shop's Silver / Gold-Brass filter
lines.push("-- Material finishes");
lines.push(`insert into public.material_finishes (slug, name, sort_order) values ('silver', 'Silver', 0) on conflict (slug) do nothing;`);
lines.push(`insert into public.material_finishes (slug, name, sort_order) values ('gold-brass', 'Gold / Brass', 1) on conflict (slug) do nothing;`);
lines.push("");

// Products
lines.push("-- Products");
for (const p of products) {
  const kind = p.slug === "kilele-hair-pin-set" ? "SET" : "INDIVIDUAL_PIECE";
  lines.push(
    `insert into public.products (slug, name, description, care_instructions, shipping_info, returns_info, base_price, cost_price, product_kind, is_bestseller, materials, created_at) values (${sql(p.slug)}, ${sql(p.name)}, ${sql(p.description)}, ${sql(p.careInstructions)}, ${sql(p.shippingInfo)}, ${sql(p.returnsInfo)}, ${p.price}, ${getCostPrice(p)}, ${sql(kind)}, ${Boolean(p.isBestseller)}, ${arr(p.materials)}, ${sql(p.createdAt)}::timestamptz) on conflict (slug) do nothing;`
  );
}
lines.push("");

// product_categories
lines.push("-- Product categories");
for (const p of products) {
  lines.push(
    `insert into public.product_categories (product_id, category_id) select pr.id, ca.id from public.products pr, public.categories ca where pr.slug = ${sql(p.slug)} and ca.slug = ${sql(p.category)} on conflict do nothing;`
  );
}
lines.push("");

// product_collections
lines.push("-- Product collections");
for (const p of products) {
  const collectionSlugs = [...p.collections, ...(FOR_MEN_SLUGS.includes(p.slug) ? ["for-men"] : [])];
  for (const slug of collectionSlugs) {
    lines.push(
      `insert into public.product_collections (product_id, collection_id) select pr.id, co.id from public.products pr, public.collections co where pr.slug = ${sql(p.slug)} and co.slug = ${sql(slug)} on conflict do nothing;`
    );
  }
}
lines.push("");

// product_material_finishes
lines.push("-- Product material finishes");
for (const p of products) {
  for (const finishSlug of materialFinishSlugs(p)) {
    lines.push(
      `insert into public.product_material_finishes (product_id, material_finish_id) select pr.id, mf.id from public.products pr, public.material_finishes mf where pr.slug = ${sql(p.slug)} and mf.slug = ${sql(finishSlug)} on conflict do nothing;`
    );
  }
}
lines.push("");

// product_options + product_option_values
lines.push("-- Product options and values");
for (const p of products) {
  const hasColour = p.variants.some((v) => v.colour);
  const hasSize = p.variants.some((v) => v.size);
  if (hasColour) {
    lines.push(
      `insert into public.product_options (product_id, name, display_order) select id, 'Colour', 0 from public.products where slug = ${sql(p.slug)} on conflict (product_id, name) do nothing;`
    );
    const colours = [...new Set(p.variants.map((v) => v.colour).filter(Boolean))] as string[];
    colours.forEach((colour, i) => {
      lines.push(
        `insert into public.product_option_values (option_id, value, display_order) select po.id, ${sql(colour)}, ${i} from public.product_options po join public.products pr on pr.id = po.product_id where pr.slug = ${sql(p.slug)} and po.name = 'Colour' on conflict (option_id, value) do nothing;`
      );
    });
  }
  if (hasSize) {
    lines.push(
      `insert into public.product_options (product_id, name, display_order) select id, 'Size', 1 from public.products where slug = ${sql(p.slug)} on conflict (product_id, name) do nothing;`
    );
    const sizes = [...new Set(p.variants.map((v) => v.size).filter(Boolean))] as string[];
    sizes.forEach((size, i) => {
      lines.push(
        `insert into public.product_option_values (option_id, value, display_order) select po.id, ${sql(size)}, ${i} from public.product_options po join public.products pr on pr.id = po.product_id where pr.slug = ${sql(p.slug)} and po.name = 'Size' on conflict (option_id, value) do nothing;`
      );
    });
  }
}
lines.push("");

// product_variants
lines.push("-- Product variants");
for (const p of products) {
  for (const v of p.variants) {
    lines.push(
      `insert into public.product_variants (product_id, sku) select id, ${sql(v.sku)} from public.products where slug = ${sql(p.slug)} on conflict (sku) do nothing;`
    );
  }
}
lines.push("");

// variant_option_values
lines.push("-- Variant option value links");
for (const p of products) {
  for (const v of p.variants) {
    if (v.colour) {
      lines.push(
        `insert into public.variant_option_values (variant_id, option_value_id) select pv.id, pov.id from public.product_variants pv join public.product_option_values pov on pov.value = ${sql(v.colour)} join public.product_options po on po.id = pov.option_id and po.name = 'Colour' join public.products pr on pr.id = po.product_id where pv.sku = ${sql(v.sku)} and pr.slug = ${sql(p.slug)} on conflict do nothing;`
      );
    }
    if (v.size) {
      lines.push(
        `insert into public.variant_option_values (variant_id, option_value_id) select pv.id, pov.id from public.product_variants pv join public.product_option_values pov on pov.value = ${sql(v.size)} join public.product_options po on po.id = pov.option_id and po.name = 'Size' join public.products pr on pr.id = po.product_id where pv.sku = ${sql(v.sku)} and pr.slug = ${sql(p.slug)} on conflict do nothing;`
      );
    }
  }
}
lines.push("");

// inventory
lines.push("-- Inventory");
for (const p of products) {
  for (const v of p.variants) {
    lines.push(
      `insert into public.inventory (variant_id, quantity_on_hand, reorder_level) select id, ${v.stock}, 2 from public.product_variants where sku = ${sql(v.sku)} on conflict (variant_id) do nothing;`
    );
  }
}
lines.push("");

// product_media
lines.push("-- Product media (placeholder markers — see components/ui/EditorialImage.tsx)");
for (const p of products) {
  p.images.forEach((image, i) => {
    lines.push(
      `insert into public.product_media (product_id, storage_path, alt_text, media_kind, sort_order, is_primary) select id, ${sql(placeholderPath(image))}, ${sql(image.alt)}, 'PRODUCT', ${i}, ${i === 0} from public.products where slug = ${sql(p.slug)};`
    );
  });
  if (p.wornImage) {
    lines.push(
      `insert into public.product_media (product_id, storage_path, alt_text, media_kind, sort_order, is_primary) select id, ${sql(placeholderPath(p.wornImage))}, ${sql(p.wornImage.alt)}, 'WORN', 0, false from public.products where slug = ${sql(p.slug)};`
    );
  }
}
lines.push("");

// Deals
lines.push("-- Deals");
for (const d of deals) {
  lines.push(
    `insert into public.deals (title, placement, discount_percent, starts_at, ends_at, is_active) select ${sql(d.title)}, 'homepage', ${d.discountPercent}, ${sql(d.startsAt)}::timestamptz, ${sql(d.endsAt)}::timestamptz, ${d.active} where not exists (select 1 from public.deals where title = ${sql(d.title)});`
  );
  for (const productId of d.productIds) {
    const product = products.find((p) => p.id === productId);
    if (!product) continue;
    lines.push(
      `insert into public.deal_products (deal_id, product_id) select de.id, pr.id from public.deals de, public.products pr where de.title = ${sql(d.title)} and pr.slug = ${sql(product.slug)} on conflict do nothing;`
    );
  }
}
lines.push("");

lines.push("commit;");

console.log(lines.join("\n"));
