-- Aurum Entonet core commerce schema. Apply with `supabase db push` after linking a project.
create extension if not exists "pgcrypto";

create type public.user_role as enum ('CUSTOMER', 'ASSISTANT', 'ADMIN');
create type public.product_kind as enum ('SET', 'INDIVIDUAL_PIECE');
create type public.order_status as enum ('PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PROCESSING', 'READY_FOR_COLLECTION', 'DISPATCHED', 'IN_TRANSIT', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'REFUNDED');
create type public.fulfilment_method as enum ('DELIVERY', 'COLLECTION');
create type public.payment_provider as enum ('MPESA', 'STRIPE');
create type public.payment_status as enum ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.user_role not null default 'CUSTOMER',
  full_name text,
  phone text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.customer_preferences (customer_id uuid primary key references public.profiles(id) on delete cascade, marketing_email boolean not null default false, order_notifications boolean not null default true, updated_at timestamptz not null default now());
create table public.customer_addresses (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.profiles(id) on delete cascade, label text not null default 'Address', recipient_name text not null, phone text not null, address_line_1 text not null, address_line_2 text, city text not null, region text, country_code text not null default 'KE', postal_code text, is_default boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table public.categories (id uuid primary key default gen_random_uuid(), slug text unique not null, name text unique not null, sort_order integer not null default 0, is_active boolean not null default true, created_at timestamptz not null default now());
create table public.collections (id uuid primary key default gen_random_uuid(), slug text unique not null, name text unique not null, description text, audience text, sort_order integer not null default 0, is_active boolean not null default true, created_at timestamptz not null default now());
create table public.material_finishes (id uuid primary key default gen_random_uuid(), slug text unique not null, name text unique not null, is_active boolean not null default true, sort_order integer not null default 0);

create table public.products (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, description text not null default '', care_instructions text, shipping_info text, returns_info text, base_price numeric(12,2) not null check (base_price >= 0), cost_price numeric(12,2) check (cost_price >= 0), product_kind public.product_kind not null default 'INDIVIDUAL_PIECE', is_active boolean not null default true, is_featured boolean not null default false, is_bestseller boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.product_categories (product_id uuid not null references public.products(id) on delete cascade, category_id uuid not null references public.categories(id) on delete restrict, primary key(product_id, category_id));
create table public.product_collections (product_id uuid not null references public.products(id) on delete cascade, collection_id uuid not null references public.collections(id) on delete restrict, primary key(product_id, collection_id));
create table public.product_material_finishes (product_id uuid not null references public.products(id) on delete cascade, material_finish_id uuid not null references public.material_finishes(id) on delete restrict, primary key(product_id, material_finish_id));
create table public.product_options (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, name text not null, display_order integer not null default 0, unique(product_id, name));
create table public.product_option_values (id uuid primary key default gen_random_uuid(), option_id uuid not null references public.product_options(id) on delete cascade, value text not null, display_order integer not null default 0, unique(option_id, value));
create table public.product_variants (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, sku text unique not null, price numeric(12,2), cost_price numeric(12,2), is_active boolean not null default true, created_at timestamptz not null default now());
create table public.variant_option_values (variant_id uuid not null references public.product_variants(id) on delete cascade, option_value_id uuid not null references public.product_option_values(id) on delete cascade, primary key(variant_id, option_value_id));
create table public.product_media (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, variant_id uuid references public.product_variants(id) on delete cascade, storage_path text not null, alt_text text, media_kind text not null check (media_kind in ('PRODUCT', 'WORN', 'EDITORIAL')), sort_order integer not null default 0, is_primary boolean not null default false, created_at timestamptz not null default now());
create table public.inventory (variant_id uuid primary key references public.product_variants(id) on delete cascade, quantity_on_hand integer not null default 0 check (quantity_on_hand >= 0), quantity_reserved integer not null default 0 check (quantity_reserved >= 0 and quantity_reserved <= quantity_on_hand), reorder_level integer not null default 0 check (reorder_level >= 0), updated_at timestamptz not null default now());
create table public.inventory_movements (id uuid primary key default gen_random_uuid(), variant_id uuid not null references public.product_variants(id) on delete restrict, quantity_delta integer not null, reason text not null, reference_type text, reference_id uuid, actor_id uuid references public.profiles(id), created_at timestamptz not null default now());

create table public.carts (id uuid primary key default gen_random_uuid(), customer_id uuid unique not null references public.profiles(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.cart_items (id uuid primary key default gen_random_uuid(), cart_id uuid not null references public.carts(id) on delete cascade, variant_id uuid not null references public.product_variants(id) on delete restrict, quantity integer not null check(quantity > 0), unique(cart_id, variant_id));
create table public.wishlists (id uuid primary key default gen_random_uuid(), customer_id uuid unique not null references public.profiles(id) on delete cascade, created_at timestamptz not null default now());
create table public.wishlist_items (wishlist_id uuid not null references public.wishlists(id) on delete cascade, product_id uuid not null references public.products(id) on delete cascade, created_at timestamptz not null default now(), primary key(wishlist_id, product_id));

create table public.shipping_zones (id uuid primary key default gen_random_uuid(), name text unique not null, country_codes text[] not null default '{}', is_international boolean not null default false, is_active boolean not null default true);
create table public.shipping_rates (id uuid primary key default gen_random_uuid(), shipping_zone_id uuid not null references public.shipping_zones(id) on delete cascade, name text not null, amount numeric(12,2) not null check(amount >= 0), min_order_amount numeric(12,2), is_active boolean not null default true);
create table public.orders (id uuid primary key default gen_random_uuid(), order_number text unique not null default ('AE-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))), customer_id uuid not null references public.profiles(id), status public.order_status not null default 'PAYMENT_PENDING', fulfilment public.fulfilment_method not null, shipping_address jsonb, shipping_rate_id uuid references public.shipping_rates(id), subtotal numeric(12,2) not null check(subtotal >= 0), shipping_total numeric(12,2) not null default 0 check(shipping_total >= 0), discount_total numeric(12,2) not null default 0 check(discount_total >= 0), total numeric(12,2) not null check(total >= 0), currency text not null default 'KES', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id) on delete set null, variant_id uuid references public.product_variants(id) on delete set null, product_name text not null, variant_name text not null, sku text, quantity integer not null check(quantity > 0), unit_price numeric(12,2) not null check(unit_price >= 0), unit_cost numeric(12,2) check(unit_cost >= 0), image_path text, created_at timestamptz not null default now());
create table public.order_status_history (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, status public.order_status not null, note text, actor_id uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.order_notes (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, note text not null, is_customer_visible boolean not null default false, actor_id uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.order_personalized_messages (order_id uuid primary key references public.orders(id) on delete cascade, recipient_name text not null, message text not null, created_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, provider public.payment_provider not null, status public.payment_status not null default 'PENDING', amount numeric(12,2) not null check(amount >= 0), provider_reference text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.payment_transactions (id uuid primary key default gen_random_uuid(), payment_id uuid not null references public.payments(id) on delete cascade, transaction_type text not null, amount numeric(12,2), provider_reference text, payload jsonb, created_at timestamptz not null default now());
create table public.payment_events (id uuid primary key default gen_random_uuid(), payment_id uuid references public.payments(id) on delete cascade, provider text not null, event_key text unique not null, payload jsonb not null, created_at timestamptz not null default now());
create table public.shipments (id uuid primary key default gen_random_uuid(), order_id uuid unique not null references public.orders(id) on delete cascade, carrier text, tracking_number text, status text, dispatched_at timestamptz, delivered_at timestamptz, updated_at timestamptz not null default now());

create table public.contact_inquiries (id uuid primary key default gen_random_uuid(), name text not null, email text not null, phone text, subject text not null, message text not null, status text not null default 'NEW', created_at timestamptz not null default now());
create table public.email_messages (id uuid primary key default gen_random_uuid(), order_id uuid references public.orders(id) on delete set null, inquiry_id uuid references public.contact_inquiries(id) on delete set null, recipient text not null, subject text not null, event_type text not null, provider_message_id text, status text not null default 'QUEUED', created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.profiles(id) on delete cascade, title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create table public.deals (id uuid primary key default gen_random_uuid(), title text not null, placement text not null, discount_percent numeric(5,2) check(discount_percent >= 0 and discount_percent <= 100), starts_at timestamptz not null, ends_at timestamptz not null, is_active boolean not null default true, check(ends_at > starts_at));
create table public.deal_products (deal_id uuid not null references public.deals(id) on delete cascade, product_id uuid not null references public.products(id) on delete cascade, primary key(deal_id, product_id));
create table public.business_expenses (id uuid primary key default gen_random_uuid(), expense_date date not null, category text not null, description text, amount numeric(12,2) not null check(amount >= 0), created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, before_data jsonb, after_data jsonb, created_at timestamptz not null default now());
create table public.content_blocks (id uuid primary key default gen_random_uuid(), key text unique not null, content jsonb not null default '{}'::jsonb, is_active boolean not null default true, updated_by uuid references public.profiles(id), updated_at timestamptz not null default now());

create or replace function public.is_staff() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.profiles where id = auth.uid() and role in ('ASSISTANT', 'ADMIN') and is_active) $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.profiles where id = auth.uid() and role = 'ADMIN' and is_active) $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id, full_name) values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name')); insert into public.customer_preferences(customer_id) values(new.id); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security; alter table public.customer_preferences enable row level security; alter table public.customer_addresses enable row level security; alter table public.categories enable row level security; alter table public.collections enable row level security; alter table public.material_finishes enable row level security; alter table public.products enable row level security; alter table public.product_categories enable row level security; alter table public.product_collections enable row level security; alter table public.product_material_finishes enable row level security; alter table public.product_options enable row level security; alter table public.product_option_values enable row level security; alter table public.product_variants enable row level security; alter table public.variant_option_values enable row level security; alter table public.product_media enable row level security; alter table public.inventory enable row level security; alter table public.inventory_movements enable row level security; alter table public.carts enable row level security; alter table public.cart_items enable row level security; alter table public.wishlists enable row level security; alter table public.wishlist_items enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.order_status_history enable row level security; alter table public.order_notes enable row level security; alter table public.order_personalized_messages enable row level security; alter table public.payments enable row level security; alter table public.shipments enable row level security; alter table public.notifications enable row level security; alter table public.contact_inquiries enable row level security; alter table public.deals enable row level security; alter table public.deal_products enable row level security; alter table public.shipping_zones enable row level security; alter table public.shipping_rates enable row level security; alter table public.business_expenses enable row level security; alter table public.audit_logs enable row level security; alter table public.content_blocks enable row level security;

create policy "profiles own read" on public.profiles for select using (id = auth.uid() or public.is_admin()); create policy "profiles own update" on public.profiles for update using (id = auth.uid() or public.is_admin()) with check (id = auth.uid() or public.is_admin());
create policy "customer own preferences" on public.customer_preferences for all using(customer_id = auth.uid()) with check(customer_id = auth.uid()); create policy "customer own addresses" on public.customer_addresses for all using(customer_id = auth.uid()) with check(customer_id = auth.uid());
create policy "public catalogue read" on public.categories for select using(is_active or public.is_staff()); create policy "public collections read" on public.collections for select using(is_active or public.is_staff()); create policy "public finishes read" on public.material_finishes for select using(is_active or public.is_staff()); create policy "public products read" on public.products for select using(is_active or public.is_staff()); create policy "public product relations read" on public.product_categories for select using(true); create policy "public product collections read" on public.product_collections for select using(true); create policy "public product finishes read" on public.product_material_finishes for select using(true); create policy "public options read" on public.product_options for select using(true); create policy "public option values read" on public.product_option_values for select using(true); create policy "public variants read" on public.product_variants for select using(is_active or public.is_staff()); create policy "public variant values read" on public.variant_option_values for select using(true); create policy "public media read" on public.product_media for select using(true); create policy "staff inventory read" on public.inventory for select using(public.is_staff()); create policy "staff inventory movements" on public.inventory_movements for select using(public.is_staff());
create policy "staff catalogue write" on public.products for all using(public.is_staff()) with check(public.is_staff()); create policy "staff categories write" on public.categories for all using(public.is_staff()) with check(public.is_staff()); create policy "staff collections write" on public.collections for all using(public.is_staff()) with check(public.is_staff()); create policy "staff finishes write" on public.material_finishes for all using(public.is_staff()) with check(public.is_staff()); create policy "staff product relations write" on public.product_categories for all using(public.is_staff()) with check(public.is_staff()); create policy "staff product collections write" on public.product_collections for all using(public.is_staff()) with check(public.is_staff()); create policy "staff product finishes write" on public.product_material_finishes for all using(public.is_staff()) with check(public.is_staff()); create policy "staff options write" on public.product_options for all using(public.is_staff()) with check(public.is_staff()); create policy "staff option values write" on public.product_option_values for all using(public.is_staff()) with check(public.is_staff()); create policy "staff variants write" on public.product_variants for all using(public.is_staff()) with check(public.is_staff()); create policy "staff variant values write" on public.variant_option_values for all using(public.is_staff()) with check(public.is_staff()); create policy "staff media write" on public.product_media for all using(public.is_staff()) with check(public.is_staff()); create policy "staff inventory write" on public.inventory for all using(public.is_staff()) with check(public.is_staff()); create policy "staff inventory movement write" on public.inventory_movements for insert with check(public.is_staff());
create policy "own cart" on public.carts for all using(customer_id = auth.uid()) with check(customer_id = auth.uid()); create policy "own cart items" on public.cart_items for all using(exists(select 1 from public.carts c where c.id = cart_id and c.customer_id = auth.uid())) with check(exists(select 1 from public.carts c where c.id = cart_id and c.customer_id = auth.uid())); create policy "own wishlist" on public.wishlists for all using(customer_id = auth.uid()) with check(customer_id = auth.uid()); create policy "own wishlist items" on public.wishlist_items for all using(exists(select 1 from public.wishlists w where w.id = wishlist_id and w.customer_id = auth.uid())) with check(exists(select 1 from public.wishlists w where w.id = wishlist_id and w.customer_id = auth.uid()));
create policy "own orders or staff" on public.orders for select using(customer_id = auth.uid() or public.is_staff()); create policy "own order items or staff" on public.order_items for select using(exists(select 1 from public.orders o where o.id = order_id and (o.customer_id = auth.uid() or public.is_staff()))); create policy "own order history or staff" on public.order_status_history for select using(exists(select 1 from public.orders o where o.id = order_id and (o.customer_id = auth.uid() or public.is_staff()))); create policy "own messages or staff" on public.order_personalized_messages for select using(exists(select 1 from public.orders o where o.id = order_id and (o.customer_id = auth.uid() or public.is_staff()))); create policy "staff orders manage" on public.orders for update using(public.is_staff()); create policy "staff order history write" on public.order_status_history for insert with check(public.is_staff()); create policy "staff notes" on public.order_notes for all using(public.is_staff()) with check(public.is_staff()); create policy "staff payments read" on public.payments for select using(public.is_staff()); create policy "staff shipments" on public.shipments for all using(public.is_staff()) with check(public.is_staff());
create policy "own notifications" on public.notifications for select using(customer_id = auth.uid()); create policy "public active deals" on public.deals for select using(is_active or public.is_staff()); create policy "public deal products" on public.deal_products for select using(true); create policy "staff deals write" on public.deals for all using(public.is_staff()) with check(public.is_staff()); create policy "staff deal product write" on public.deal_products for all using(public.is_staff()) with check(public.is_staff()); create policy "public shipping read" on public.shipping_zones for select using(is_active or public.is_staff()); create policy "public rates read" on public.shipping_rates for select using(is_active or public.is_staff()); create policy "admin expenses" on public.business_expenses for all using(public.is_admin()) with check(public.is_admin()); create policy "admin audit logs" on public.audit_logs for select using(public.is_admin()); create policy "admin content" on public.content_blocks for all using(public.is_admin()) with check(public.is_admin()); create policy "staff inquiries" on public.contact_inquiries for select using(public.is_staff()); create policy "public inquiry insert" on public.contact_inquiries for insert with check(true);

insert into storage.buckets(id, name, public) values ('product-media', 'product-media', true) on conflict do nothing;
create policy "product media public read" on storage.objects for select using(bucket_id = 'product-media'); create policy "staff product media upload" on storage.objects for insert with check(bucket_id = 'product-media' and public.is_staff()); create policy "staff product media update" on storage.objects for update using(bucket_id = 'product-media' and public.is_staff()); create policy "staff product media delete" on storage.objects for delete using(bucket_id = 'product-media' and public.is_staff());
